name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: renyas/yourimagename:latest
          platforms: linux/arm64

validate_and_tests:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - uses: actions/checkout@v3  # This step is necessary to access the repository files

    - name: Setup kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Create .kube directory
      run: mkdir -p $HOME/.kube

    - name: Set up KUBECONFIG
      run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Infrastructure Test - Check Kubernetes Nodes
      run: kubectl get nodes

    - name: Infrastructure Test - Check Kubernetes Pods
      run: kubectl get pods --all-namespaces

    - name: Infrastructure Test - Check Kubernetes Services
      run: kubectl get services --all-namespaces

    - name: Deploy to Kubernetes 
      run: |
        kubectl apply -f kubernetes-config/deploy.yaml
        kubectl rollout status deployment/group03 -n group03

    - name: Restart Deployment
      run: kubectl rollout restart deployment/group03 -n group03