name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platform: linux/arm64
          push: true
          tags: renyas/yourimagename:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Print current image used in deployment
        run: kubectl get deployment ahw -n group03 -o=jsonpath='{.spec.template.spec.containers[0].image}'

      - name: Replace image in deploy.yaml
        run: sed -i 's|renyas/yourimagename:.*|renyas/yourimagename:latest|g' kubernetes-config/deploy.yaml

      - name: Apply Kubernetes deployment
        run: kubectl apply -f kubernetes-config/deploy.yaml

      - name: Wait for deployment to roll out
        run: kubectl rollout status deployment ahw -n group03

      - name: Print updated image used in deployment
        run: kubectl get deployment ahw -n group03 -o=jsonpath='{.spec.template.spec.containers[0].image}'
