name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: renyas/yourimagename:latest
          platforms: linux/arm64

      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Set up KUBECONFIG
        run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Install Kubeval
        run: |
          curl -sL https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz | tar zx
          sudo cp kubeval /usr/local/bin

      - name: Validate Kubernetes Configuration
        run: kubeval kubernetes-config/deploy.yaml --ignore-missing-schemas

      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2 curl
          curl -fsSL https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run Load Testing
        run: k6 run ./scripts/load-test.js

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Kubernetes Configurations for Vulnerabilities
        run: trivy config kubernetes-config/

      - name: Scan Container Images for Vulnerabilities
        run: |
          # Assuming your Docker images are listed in a file or can be dynamically retrieved
          cat docker_images_list.txt | xargs -I {} trivy image {}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes-config/deploy.yaml
          kubectl rollout status deployment/group03 -n group03
