name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: renyas/yourimagename:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Verify Kubernetes context
        run: kubectl config current-context

      - name: Describe deployment for debug
        run: kubectl describe deployment ahw -n group03

      - name: Deploy to Kubernetes using kubectl patch
        env:
          DEPLOYMENT_NAME: ahw
          NAMESPACE: group03
        run: |
          kubectl patch deployment ${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }} --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"renyas/yourimagename:latest"}]'
